/**
 * \file Template.c
 * \brief Demo Template
 *
 * \version iLLD_Demos_1_0_1_11_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "EvadcQueueTransferDemo.h"
#include <Cpu/Std/IfxCpu.h>

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
App_EvadcQueueTransfer g_EvadcQueueTransfer; /**< \brief Demo information */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void EvadcQueueTransferDemo_init(void)
{
    /* Evadc Configuration */

    /* create configuration*/
    IfxEvadc_Adc_Config adcConfig;
    IfxEvadc_Adc_initModuleConfig(&adcConfig, &MODULE_EVADC);

    /* initialize module*/
    IfxEvadc_Adc_initModule(&g_EvadcQueueTransfer.evadc, &adcConfig);

    /* create group config*/
    IfxEvadc_Adc_GroupConfig adcGroupConfig;
    IfxEvadc_Adc_initGroupConfig(&adcGroupConfig, &g_EvadcQueueTransfer.evadc);

    /* with group 1 */
    adcGroupConfig.groupId = IfxEvadc_GroupId_1;
    adcGroupConfig.master  = adcGroupConfig.groupId;

    /* enable all queue source */
    adcGroupConfig.arbiter.requestSlotQueue0Enabled  = TRUE; // enable Queue0 mode
    adcGroupConfig.arbiter.requestSlotQueue1Enabled  = TRUE; // enable Queue1 mode
    adcGroupConfig.arbiter.requestSlotQueue2Enabled  = TRUE; // enable Queue2 mode

    /* enable all gates in "always" mode (no edge detection)*/
    adcGroupConfig.queueRequest[0].triggerConfig.gatingMode = IfxEvadc_GatingMode_always;
    adcGroupConfig.queueRequest[1].triggerConfig.gatingMode = IfxEvadc_GatingMode_always;
    adcGroupConfig.queueRequest[2].triggerConfig.gatingMode = IfxEvadc_GatingMode_always;

    /* initialize the group*/
    IfxEvadc_Adc_initGroup(&g_EvadcQueueTransfer.adcGroup, &adcGroupConfig);
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void EvadcQueueTransferDemo_run(void)
{
    printf("EvadcQueueTransferDemo_run() called\n");


    printf("Queued transfer of a single channel\n");

    {
        /* create channel config*/
        IfxEvadc_Adc_ChannelConfig adcChannelConfig;
        IfxEvadc_Adc_initChannelConfig(&adcChannelConfig, &g_EvadcQueueTransfer.adcGroup);

        IfxEvadc_RequestSource requestSource = IfxEvadc_RequestSource_queue0;

        /* change channel (default is ChannelId_0, change to ChannelId_3)*/
        adcChannelConfig.channelId = IfxEvadc_ChannelId_3;

        /* initialize the channel*/
        IfxEvadc_Adc_Channel adcChannel;
        IfxEvadc_Adc_initChannel(&adcChannel, &adcChannelConfig);

        /* Add channel to queue with refill enabled*/
        IfxEvadc_Adc_addToQueue(&adcChannel,requestSource,IFXEVADC_QUEUE_REFILL);

        /* start the Queue*/
        IfxEvadc_Adc_startQueue(&g_EvadcQueueTransfer.adcGroup,requestSource);

        /* get 10 results */
        uint32 i;

        for (i = 0; i < 10; ++i)
        {
            unsigned     group   = adcChannel.group->groupId;
            unsigned     channel = adcChannel.channel;

            /* wait for valid result*/
            Ifx_EVADC_G_RES conversionResult;

            do
            {
                conversionResult = IfxEvadc_Adc_getResult(&adcChannel);
            } while (!conversionResult.B.VF);

            /* print result, check with expected value*/
            {
                uint32 actual = conversionResult.B.RESULT;

                /* FIXME result verification pending ??*/
                printf("Group %d Channel : %d, result : %u\n", group, channel, actual);
            }
        }

        /* stop the queue */
        IfxEvadc_Adc_clearQueue(&g_EvadcQueueTransfer.adcGroup,requestSource);
    }

    printf("Queued transfers of three channels\n");

    {
        uint32                    chnIx;
        /* IMPORTANT: for deterministic results we have to disable the queue gate
         * while filling the queue, otherwise results could be output in the wrong order */
        IfxEvadc_RequestSource requestSource = IfxEvadc_RequestSource_queue0;
        IfxEvadc_GatingMode savedGate =  IfxEvadc_getQueueSlotGatingMode(g_EvadcQueueTransfer.adcGroup.group,requestSource);
        IfxEvadc_GatingSource gatingSource = IfxEvadc_getQueueSlotGatingSource(g_EvadcQueueTransfer.adcGroup.group, requestSource );

        /* create channel config */
        IfxEvadc_Adc_ChannelConfig adcChannelConfig[3];
        IfxEvadc_Adc_Channel       adcChannel[3];

        for (chnIx = 0; chnIx < 3; ++chnIx)
        {
            IfxEvadc_Adc_initChannelConfig(&adcChannelConfig[chnIx], &g_EvadcQueueTransfer.adcGroup);

            adcChannelConfig[chnIx].channelId      = (IfxEvadc_ChannelId)(chnIx);
            adcChannelConfig[chnIx].resultRegister = IfxEvadc_ChannelResult_1; /* use result register #1 for all channels */

            /* initialize the channel */
            IfxEvadc_Adc_initChannel(&adcChannel[chnIx], &adcChannelConfig[chnIx]);

            /* Add channel to queue with refill enabled */
            IfxEvadc_Adc_addToQueue(&adcChannel[chnIx], requestSource,IFXEVADC_QUEUE_REFILL);
        }

        /* restore previous gate config */
        IfxEvadc_setQueueSlotGatingConfig(g_EvadcQueueTransfer.adcGroup.group, gatingSource, savedGate, requestSource );

        /* start the Queue */
        IfxEvadc_Adc_startQueue(&g_EvadcQueueTransfer.adcGroup,requestSource); /* the queue has already been started in previous test */

        /* get 10 results for all 3 channels and store in temporary buffer */
        Ifx_EVADC_G_RES resultTrace[3 * 10];

        uint32       i;

        for (i = 0; i < 3 * 10; ++i)
        {
            unsigned     chnIx = i % 3;

            /* wait for valid result */
            Ifx_EVADC_G_RES conversionResult;

            do
            {
                conversionResult = IfxEvadc_Adc_getResult(&adcChannel[chnIx]);
            } while (!conversionResult.B.VF);

            /* store result */
            resultTrace[i] = conversionResult;
        }

        /* stop the queue */
        IfxEvadc_Adc_clearQueue(&g_EvadcQueueTransfer.adcGroup,requestSource);

        /* check results in buffer */
        for (i = 0; i < 3 * 10; ++i)
        {
            unsigned chnIx   = i % 3;
            unsigned group   = adcChannel[chnIx].group->groupId;
            unsigned channel = adcChannel[chnIx].channel;
            uint32   actual  = resultTrace[i].B.RESULT;
            printf("Group %d Channel : %d, result : %u\n", group, channel, actual);
        }
    }
}

unsigned int EvadcQueueTransfer_ch_run(unsigned char channel)
{
    uint32 actual;
    {
        /* create channel config*/
        IfxEvadc_Adc_ChannelConfig adcChannelConfig;
        IfxEvadc_Adc_initChannelConfig(&adcChannelConfig, &g_EvadcQueueTransfer.adcGroup);

        IfxEvadc_RequestSource requestSource = IfxEvadc_RequestSource_queue0;

        /* change channel (default is ChannelId_0, change to ChannelId_3)*/
        //adcChannelConfig.channelId = IfxEvadc_ChannelId_3;
		adcChannelConfig.channelId = channel;

        /* initialize the channel*/
        IfxEvadc_Adc_Channel adcChannel;
        IfxEvadc_Adc_initChannel(&adcChannel, &adcChannelConfig);

        /* Add channel to queue with refill enabled*/
        IfxEvadc_Adc_addToQueue(&adcChannel,requestSource,IFXEVADC_QUEUE_REFILL);

        /* start the Queue*/
        IfxEvadc_Adc_startQueue(&g_EvadcQueueTransfer.adcGroup,requestSource);

        /* get 10 results */
        uint32 i;

        for (i = 0; i < 3; ++i)
        {
            /* wait for valid result*/
            Ifx_EVADC_G_RES conversionResult;

            do
            {
                conversionResult = IfxEvadc_Adc_getResult(&adcChannel);
            } while (!conversionResult.B.VF);

            actual = conversionResult.B.RESULT;
        }

        /* stop the queue */
        IfxEvadc_Adc_clearQueue(&g_EvadcQueueTransfer.adcGroup,requestSource);
    }
    return actual;
}

