/**
 * \file FlashDemo.h
 * \brief  Flash erase & program Demo
 *
 * \version iLLD_Demos_1_0_1_11_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 * \defgroup IfxLld_Demo_FlashDemo_SrcDoc_Main Demo Source
 * \ingroup IfxLld_Demo_FlashDemo_SrcDoc
 * \defgroup IfxLld_Demo_FlashDemo_SrcDoc_Main_Interrupt Interrupts
 * \ingroup IfxLld_Demo_FlashDemo_SrcDoc_Main
 */

#ifndef FLASHDEMO_H
#define FLASHDEMO_H 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include <Ifx_Types.h>
#include "IfxFlash.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/** \brief P Flash global data */
typedef struct
{
/** \brief Function pointers of Erase & program routines which are relocated to different memory (PSPR).
 *  The function pointers are used to execute the relocated routines
 */
    struct
    {
        void (*eraseSector)(uint32);
        uint8 (*waitUnbusy)(uint32, IfxFlash_FlashType);
        uint8 (*enterPageMode)(uint32);
        void (*loadPage2X32)(uint32, uint32, uint32);
        void (*writePage)(uint32);
        void (*pFlashErase)(uint32, uint32);
        void (*pFlashProgram)(uint32, uint32, uint32, uint32);
    }                  command;

    uint32             sector;        /**< \brief Flash sector to be erased & programmed */
    uint32             startPage;     /**< \brief Page from which programming starts */
    uint32             numberOfPages; /**< \brief No of pages to be programmed */
    IfxFlash_FlashType flashType;     /**< \brief Flash type ussed for the erase/program */
} App_Pflash;

/** \brief D Flash global data */
typedef struct
{
    uint32             sector;              /**< \brief Flash sector to be erased & programmed */
    uint32             startPage;           /**< \brief Page from which programming starts */
    uint32             numberOfPages;       /**< \brief No of pages to be programmed */
    IfxFlash_FlashType flashType;           /**< \brief Flash type ussed for the erase/program */
} App_Dflash;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
IFX_EXTERN App_Pflash g_Pflash;
IFX_EXTERN App_Dflash g_Dflash;

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/
IFX_EXTERN void IfxFlashDemo_init(void);
IFX_EXTERN void IfxFlashDemo_run(void);
IFX_EXTERN void IfxFlash_erase_dflash(unsigned char sector,unsigned char sector_num);
IFX_EXTERN void IfxFlash_programme_dflash(unsigned int destpageaddr,unsigned int wordL, unsigned int wordU);

#endif
