/**
 * \file Template.h
 * \brief Demo Template
 *
 * \version iLLD_Demos_1_0_1_11_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such 
 * terms of use are agreed, use of this file is subject to following:


 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or 
 * organization obtaining a copy of the software and accompanying 
 * documentation covered by this license (the "Software") to use, reproduce,
 * display, distribute, execute, and transmit the Software, and to prepare
 * derivative works of the Software, and to permit third-parties to whom the 
 * Software is furnished to do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 *
 * \defgroup IfxLld_Demo_Template_SrcDoc_Main Demo Source
 * \ingroup IfxLld_Demo_Template_SrcDoc
 * \defgroup IfxLld_Demo_Template_SrcDoc_Main_Interrupt Interrupts
 * \ingroup IfxLld_Demo_Template_SrcDoc_Main
 */

#ifndef TEMPLATE_H
#define TEMPLATE_H 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include <Ifx_Types.h>

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
typedef struct TimPwmDemo_Info_Tag
{
	/* TIM parameters */
    uint8 TimModule;		/* Tim Module used for measurement */
    uint8 TimChannel;		/* Tim Channel used for measurement */
    float32 CaptureFrequency; /* Capture Frequency of Tim Channel */
    float32 duty_percent;	/* Duty Cycle in percentage */
    float32 frequency_hz;	/* Frequency of input PWM in Hz */
    boolean dataCoherent;	/* TRUE: data is coherent. FALSE: data is not coherent */

    /* TOM parameters */
    uint8 TomModule;	/* TOM module used for PWM generation */
    uint8 TomChannel;	/* Tom Channel used for PWM generation */
    float32 PwmFrequency;	/* Frequency of PWM generated */
    float32 pwmduty_percent;	/* duty cycle in percentage */
    uint32 pwmperiod_counts;	/* period in counts */
    uint32 pwmduty_counts;		/* duty in counts */
    float32 tomChannelFreq;	/* TOM channel frequency */

    /* counter for ISR Hits */
    uint32 isrHitCount;		/* ISR hit counts */

} TimPwmDemo_Info_T;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
IFX_EXTERN TimPwmDemo_Info_T TimPwmDemo_Info;

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/
IFX_EXTERN void TimPwmDemo_init(void);
IFX_EXTERN void TimPwmDemo_run(void);

#endif
